title: The Adventurous Armachair Foodie
author: bethealt
description: The narcissitic ravings of a wannabe foodie confined to her apartment.  I travel through the web, social media, and streaming video to develop my musings.  I hope that you find them entertaining.  We can agree to disagree, but no arguments please.
theme: minima
# social links
twitter_username: bethealt # DO NOT include the @ character, or else the build will fail!
github_username:  bethealt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
